version: "3.8"
services:
  todolist-db:
    image: postgres:latest
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: todolist
    networks:
      - todolist
networks:
  todolist: